# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/DSV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/DSV/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/DSV/build/CMakeFiles /workspaces/DSV/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/DSV/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dsv_common

# Build rule for target.
dsv_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsv_common
.PHONY : dsv_common

# fast build rule for target.
dsv_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/build
.PHONY : dsv_common/fast

#=============================================================================
# Target rules for targets named dsv_node_lib

# Build rule for target.
dsv_node_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsv_node_lib
.PHONY : dsv_node_lib

# fast build rule for target.
dsv_node_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/build
.PHONY : dsv_node_lib/fast

#=============================================================================
# Target rules for targets named dsvd

# Build rule for target.
dsvd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsvd
.PHONY : dsvd

# fast build rule for target.
dsvd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsvd.dir/build.make CMakeFiles/dsvd.dir/build
.PHONY : dsvd/fast

#=============================================================================
# Target rules for targets named dsv_wallet_lib

# Build rule for target.
dsv_wallet_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsv_wallet_lib
.PHONY : dsv_wallet_lib

# fast build rule for target.
dsv_wallet_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_wallet_lib.dir/build.make CMakeFiles/dsv_wallet_lib.dir/build
.PHONY : dsv_wallet_lib/fast

#=============================================================================
# Target rules for targets named dsv-wallet

# Build rule for target.
dsv-wallet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsv-wallet
.PHONY : dsv-wallet

# fast build rule for target.
dsv-wallet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-wallet.dir/build.make CMakeFiles/dsv-wallet.dir/build
.PHONY : dsv-wallet/fast

#=============================================================================
# Target rules for targets named dsv-cli

# Build rule for target.
dsv-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsv-cli
.PHONY : dsv-cli

# fast build rule for target.
dsv-cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-cli.dir/build.make CMakeFiles/dsv-cli.dir/build
.PHONY : dsv-cli/fast

#=============================================================================
# Target rules for targets named test_consensus

# Build rule for target.
test_consensus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_consensus
.PHONY : test_consensus

# fast build rule for target.
test_consensus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_consensus.dir/build.make CMakeFiles/test_consensus.dir/build
.PHONY : test_consensus/fast

#=============================================================================
# Target rules for targets named test_crypto

# Build rule for target.
test_crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_crypto
.PHONY : test_crypto

# fast build rule for target.
test_crypto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/build
.PHONY : test_crypto/fast

#=============================================================================
# Target rules for targets named test_serialize

# Build rule for target.
test_serialize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_serialize
.PHONY : test_serialize

# fast build rule for target.
test_serialize/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_serialize.dir/build.make CMakeFiles/test_serialize.dir/build
.PHONY : test_serialize/fast

#=============================================================================
# Target rules for targets named test_u320

# Build rule for target.
test_u320: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_u320
.PHONY : test_u320

# fast build rule for target.
test_u320/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_u320.dir/build.make CMakeFiles/test_u320.dir/build
.PHONY : test_u320/fast

cli/main.o: cli/main.c.o
.PHONY : cli/main.o

# target to build an object file
cli/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-cli.dir/build.make CMakeFiles/dsv-cli.dir/cli/main.c.o
.PHONY : cli/main.c.o

cli/main.i: cli/main.c.i
.PHONY : cli/main.i

# target to preprocess a source file
cli/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-cli.dir/build.make CMakeFiles/dsv-cli.dir/cli/main.c.i
.PHONY : cli/main.c.i

cli/main.s: cli/main.c.s
.PHONY : cli/main.s

# target to generate assembly for a file
cli/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-cli.dir/build.make CMakeFiles/dsv-cli.dir/cli/main.c.s
.PHONY : cli/main.c.s

cli/src/rpc_client.o: cli/src/rpc_client.c.o
.PHONY : cli/src/rpc_client.o

# target to build an object file
cli/src/rpc_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-cli.dir/build.make CMakeFiles/dsv-cli.dir/cli/src/rpc_client.c.o
.PHONY : cli/src/rpc_client.c.o

cli/src/rpc_client.i: cli/src/rpc_client.c.i
.PHONY : cli/src/rpc_client.i

# target to preprocess a source file
cli/src/rpc_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-cli.dir/build.make CMakeFiles/dsv-cli.dir/cli/src/rpc_client.c.i
.PHONY : cli/src/rpc_client.c.i

cli/src/rpc_client.s: cli/src/rpc_client.c.s
.PHONY : cli/src/rpc_client.s

# target to generate assembly for a file
cli/src/rpc_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-cli.dir/build.make CMakeFiles/dsv-cli.dir/cli/src/rpc_client.c.s
.PHONY : cli/src/rpc_client.c.s

common/src/dsv_consensus.o: common/src/dsv_consensus.c.o
.PHONY : common/src/dsv_consensus.o

# target to build an object file
common/src/dsv_consensus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_consensus.c.o
.PHONY : common/src/dsv_consensus.c.o

common/src/dsv_consensus.i: common/src/dsv_consensus.c.i
.PHONY : common/src/dsv_consensus.i

# target to preprocess a source file
common/src/dsv_consensus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_consensus.c.i
.PHONY : common/src/dsv_consensus.c.i

common/src/dsv_consensus.s: common/src/dsv_consensus.c.s
.PHONY : common/src/dsv_consensus.s

# target to generate assembly for a file
common/src/dsv_consensus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_consensus.c.s
.PHONY : common/src/dsv_consensus.c.s

common/src/dsv_crypto.o: common/src/dsv_crypto.c.o
.PHONY : common/src/dsv_crypto.o

# target to build an object file
common/src/dsv_crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_crypto.c.o
.PHONY : common/src/dsv_crypto.c.o

common/src/dsv_crypto.i: common/src/dsv_crypto.c.i
.PHONY : common/src/dsv_crypto.i

# target to preprocess a source file
common/src/dsv_crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_crypto.c.i
.PHONY : common/src/dsv_crypto.c.i

common/src/dsv_crypto.s: common/src/dsv_crypto.c.s
.PHONY : common/src/dsv_crypto.s

# target to generate assembly for a file
common/src/dsv_crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_crypto.c.s
.PHONY : common/src/dsv_crypto.c.s

common/src/dsv_serialize.o: common/src/dsv_serialize.c.o
.PHONY : common/src/dsv_serialize.o

# target to build an object file
common/src/dsv_serialize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_serialize.c.o
.PHONY : common/src/dsv_serialize.c.o

common/src/dsv_serialize.i: common/src/dsv_serialize.c.i
.PHONY : common/src/dsv_serialize.i

# target to preprocess a source file
common/src/dsv_serialize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_serialize.c.i
.PHONY : common/src/dsv_serialize.c.i

common/src/dsv_serialize.s: common/src/dsv_serialize.c.s
.PHONY : common/src/dsv_serialize.s

# target to generate assembly for a file
common/src/dsv_serialize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_serialize.c.s
.PHONY : common/src/dsv_serialize.c.s

common/src/dsv_u320.o: common/src/dsv_u320.c.o
.PHONY : common/src/dsv_u320.o

# target to build an object file
common/src/dsv_u320.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_u320.c.o
.PHONY : common/src/dsv_u320.c.o

common/src/dsv_u320.i: common/src/dsv_u320.c.i
.PHONY : common/src/dsv_u320.i

# target to preprocess a source file
common/src/dsv_u320.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_u320.c.i
.PHONY : common/src/dsv_u320.c.i

common/src/dsv_u320.s: common/src/dsv_u320.c.s
.PHONY : common/src/dsv_u320.s

# target to generate assembly for a file
common/src/dsv_u320.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_common.dir/build.make CMakeFiles/dsv_common.dir/common/src/dsv_u320.c.s
.PHONY : common/src/dsv_u320.c.s

node/main.o: node/main.c.o
.PHONY : node/main.o

# target to build an object file
node/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsvd.dir/build.make CMakeFiles/dsvd.dir/node/main.c.o
.PHONY : node/main.c.o

node/main.i: node/main.c.i
.PHONY : node/main.i

# target to preprocess a source file
node/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsvd.dir/build.make CMakeFiles/dsvd.dir/node/main.c.i
.PHONY : node/main.c.i

node/main.s: node/main.c.s
.PHONY : node/main.s

# target to generate assembly for a file
node/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsvd.dir/build.make CMakeFiles/dsvd.dir/node/main.c.s
.PHONY : node/main.c.s

node/src/dsv_chain.o: node/src/dsv_chain.c.o
.PHONY : node/src/dsv_chain.o

# target to build an object file
node/src/dsv_chain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_chain.c.o
.PHONY : node/src/dsv_chain.c.o

node/src/dsv_chain.i: node/src/dsv_chain.c.i
.PHONY : node/src/dsv_chain.i

# target to preprocess a source file
node/src/dsv_chain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_chain.c.i
.PHONY : node/src/dsv_chain.c.i

node/src/dsv_chain.s: node/src/dsv_chain.c.s
.PHONY : node/src/dsv_chain.s

# target to generate assembly for a file
node/src/dsv_chain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_chain.c.s
.PHONY : node/src/dsv_chain.c.s

node/src/dsv_mempool.o: node/src/dsv_mempool.c.o
.PHONY : node/src/dsv_mempool.o

# target to build an object file
node/src/dsv_mempool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_mempool.c.o
.PHONY : node/src/dsv_mempool.c.o

node/src/dsv_mempool.i: node/src/dsv_mempool.c.i
.PHONY : node/src/dsv_mempool.i

# target to preprocess a source file
node/src/dsv_mempool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_mempool.c.i
.PHONY : node/src/dsv_mempool.c.i

node/src/dsv_mempool.s: node/src/dsv_mempool.c.s
.PHONY : node/src/dsv_mempool.s

# target to generate assembly for a file
node/src/dsv_mempool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_mempool.c.s
.PHONY : node/src/dsv_mempool.c.s

node/src/dsv_p2p.o: node/src/dsv_p2p.c.o
.PHONY : node/src/dsv_p2p.o

# target to build an object file
node/src/dsv_p2p.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_p2p.c.o
.PHONY : node/src/dsv_p2p.c.o

node/src/dsv_p2p.i: node/src/dsv_p2p.c.i
.PHONY : node/src/dsv_p2p.i

# target to preprocess a source file
node/src/dsv_p2p.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_p2p.c.i
.PHONY : node/src/dsv_p2p.c.i

node/src/dsv_p2p.s: node/src/dsv_p2p.c.s
.PHONY : node/src/dsv_p2p.s

# target to generate assembly for a file
node/src/dsv_p2p.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_p2p.c.s
.PHONY : node/src/dsv_p2p.c.s

node/src/dsv_rpc.o: node/src/dsv_rpc.c.o
.PHONY : node/src/dsv_rpc.o

# target to build an object file
node/src/dsv_rpc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_rpc.c.o
.PHONY : node/src/dsv_rpc.c.o

node/src/dsv_rpc.i: node/src/dsv_rpc.c.i
.PHONY : node/src/dsv_rpc.i

# target to preprocess a source file
node/src/dsv_rpc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_rpc.c.i
.PHONY : node/src/dsv_rpc.c.i

node/src/dsv_rpc.s: node/src/dsv_rpc.c.s
.PHONY : node/src/dsv_rpc.s

# target to generate assembly for a file
node/src/dsv_rpc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_rpc.c.s
.PHONY : node/src/dsv_rpc.c.s

node/src/dsv_storage.o: node/src/dsv_storage.c.o
.PHONY : node/src/dsv_storage.o

# target to build an object file
node/src/dsv_storage.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_storage.c.o
.PHONY : node/src/dsv_storage.c.o

node/src/dsv_storage.i: node/src/dsv_storage.c.i
.PHONY : node/src/dsv_storage.i

# target to preprocess a source file
node/src/dsv_storage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_storage.c.i
.PHONY : node/src/dsv_storage.c.i

node/src/dsv_storage.s: node/src/dsv_storage.c.s
.PHONY : node/src/dsv_storage.s

# target to generate assembly for a file
node/src/dsv_storage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_node_lib.dir/build.make CMakeFiles/dsv_node_lib.dir/node/src/dsv_storage.c.s
.PHONY : node/src/dsv_storage.c.s

tests/unit/test_consensus.o: tests/unit/test_consensus.c.o
.PHONY : tests/unit/test_consensus.o

# target to build an object file
tests/unit/test_consensus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_consensus.dir/build.make CMakeFiles/test_consensus.dir/tests/unit/test_consensus.c.o
.PHONY : tests/unit/test_consensus.c.o

tests/unit/test_consensus.i: tests/unit/test_consensus.c.i
.PHONY : tests/unit/test_consensus.i

# target to preprocess a source file
tests/unit/test_consensus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_consensus.dir/build.make CMakeFiles/test_consensus.dir/tests/unit/test_consensus.c.i
.PHONY : tests/unit/test_consensus.c.i

tests/unit/test_consensus.s: tests/unit/test_consensus.c.s
.PHONY : tests/unit/test_consensus.s

# target to generate assembly for a file
tests/unit/test_consensus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_consensus.dir/build.make CMakeFiles/test_consensus.dir/tests/unit/test_consensus.c.s
.PHONY : tests/unit/test_consensus.c.s

tests/unit/test_crypto.o: tests/unit/test_crypto.c.o
.PHONY : tests/unit/test_crypto.o

# target to build an object file
tests/unit/test_crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/unit/test_crypto.c.o
.PHONY : tests/unit/test_crypto.c.o

tests/unit/test_crypto.i: tests/unit/test_crypto.c.i
.PHONY : tests/unit/test_crypto.i

# target to preprocess a source file
tests/unit/test_crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/unit/test_crypto.c.i
.PHONY : tests/unit/test_crypto.c.i

tests/unit/test_crypto.s: tests/unit/test_crypto.c.s
.PHONY : tests/unit/test_crypto.s

# target to generate assembly for a file
tests/unit/test_crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_crypto.dir/build.make CMakeFiles/test_crypto.dir/tests/unit/test_crypto.c.s
.PHONY : tests/unit/test_crypto.c.s

tests/unit/test_serialize.o: tests/unit/test_serialize.c.o
.PHONY : tests/unit/test_serialize.o

# target to build an object file
tests/unit/test_serialize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_serialize.dir/build.make CMakeFiles/test_serialize.dir/tests/unit/test_serialize.c.o
.PHONY : tests/unit/test_serialize.c.o

tests/unit/test_serialize.i: tests/unit/test_serialize.c.i
.PHONY : tests/unit/test_serialize.i

# target to preprocess a source file
tests/unit/test_serialize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_serialize.dir/build.make CMakeFiles/test_serialize.dir/tests/unit/test_serialize.c.i
.PHONY : tests/unit/test_serialize.c.i

tests/unit/test_serialize.s: tests/unit/test_serialize.c.s
.PHONY : tests/unit/test_serialize.s

# target to generate assembly for a file
tests/unit/test_serialize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_serialize.dir/build.make CMakeFiles/test_serialize.dir/tests/unit/test_serialize.c.s
.PHONY : tests/unit/test_serialize.c.s

tests/unit/test_u320.o: tests/unit/test_u320.c.o
.PHONY : tests/unit/test_u320.o

# target to build an object file
tests/unit/test_u320.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_u320.dir/build.make CMakeFiles/test_u320.dir/tests/unit/test_u320.c.o
.PHONY : tests/unit/test_u320.c.o

tests/unit/test_u320.i: tests/unit/test_u320.c.i
.PHONY : tests/unit/test_u320.i

# target to preprocess a source file
tests/unit/test_u320.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_u320.dir/build.make CMakeFiles/test_u320.dir/tests/unit/test_u320.c.i
.PHONY : tests/unit/test_u320.c.i

tests/unit/test_u320.s: tests/unit/test_u320.c.s
.PHONY : tests/unit/test_u320.s

# target to generate assembly for a file
tests/unit/test_u320.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_u320.dir/build.make CMakeFiles/test_u320.dir/tests/unit/test_u320.c.s
.PHONY : tests/unit/test_u320.c.s

wallet/main.o: wallet/main.c.o
.PHONY : wallet/main.o

# target to build an object file
wallet/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-wallet.dir/build.make CMakeFiles/dsv-wallet.dir/wallet/main.c.o
.PHONY : wallet/main.c.o

wallet/main.i: wallet/main.c.i
.PHONY : wallet/main.i

# target to preprocess a source file
wallet/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-wallet.dir/build.make CMakeFiles/dsv-wallet.dir/wallet/main.c.i
.PHONY : wallet/main.c.i

wallet/main.s: wallet/main.c.s
.PHONY : wallet/main.s

# target to generate assembly for a file
wallet/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv-wallet.dir/build.make CMakeFiles/dsv-wallet.dir/wallet/main.c.s
.PHONY : wallet/main.c.s

wallet/src/dsv_wallet.o: wallet/src/dsv_wallet.c.o
.PHONY : wallet/src/dsv_wallet.o

# target to build an object file
wallet/src/dsv_wallet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_wallet_lib.dir/build.make CMakeFiles/dsv_wallet_lib.dir/wallet/src/dsv_wallet.c.o
.PHONY : wallet/src/dsv_wallet.c.o

wallet/src/dsv_wallet.i: wallet/src/dsv_wallet.c.i
.PHONY : wallet/src/dsv_wallet.i

# target to preprocess a source file
wallet/src/dsv_wallet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_wallet_lib.dir/build.make CMakeFiles/dsv_wallet_lib.dir/wallet/src/dsv_wallet.c.i
.PHONY : wallet/src/dsv_wallet.c.i

wallet/src/dsv_wallet.s: wallet/src/dsv_wallet.c.s
.PHONY : wallet/src/dsv_wallet.s

# target to generate assembly for a file
wallet/src/dsv_wallet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsv_wallet_lib.dir/build.make CMakeFiles/dsv_wallet_lib.dir/wallet/src/dsv_wallet.c.s
.PHONY : wallet/src/dsv_wallet.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... dsv-cli"
	@echo "... dsv-wallet"
	@echo "... dsv_common"
	@echo "... dsv_node_lib"
	@echo "... dsv_wallet_lib"
	@echo "... dsvd"
	@echo "... test_consensus"
	@echo "... test_crypto"
	@echo "... test_serialize"
	@echo "... test_u320"
	@echo "... cli/main.o"
	@echo "... cli/main.i"
	@echo "... cli/main.s"
	@echo "... cli/src/rpc_client.o"
	@echo "... cli/src/rpc_client.i"
	@echo "... cli/src/rpc_client.s"
	@echo "... common/src/dsv_consensus.o"
	@echo "... common/src/dsv_consensus.i"
	@echo "... common/src/dsv_consensus.s"
	@echo "... common/src/dsv_crypto.o"
	@echo "... common/src/dsv_crypto.i"
	@echo "... common/src/dsv_crypto.s"
	@echo "... common/src/dsv_serialize.o"
	@echo "... common/src/dsv_serialize.i"
	@echo "... common/src/dsv_serialize.s"
	@echo "... common/src/dsv_u320.o"
	@echo "... common/src/dsv_u320.i"
	@echo "... common/src/dsv_u320.s"
	@echo "... node/main.o"
	@echo "... node/main.i"
	@echo "... node/main.s"
	@echo "... node/src/dsv_chain.o"
	@echo "... node/src/dsv_chain.i"
	@echo "... node/src/dsv_chain.s"
	@echo "... node/src/dsv_mempool.o"
	@echo "... node/src/dsv_mempool.i"
	@echo "... node/src/dsv_mempool.s"
	@echo "... node/src/dsv_p2p.o"
	@echo "... node/src/dsv_p2p.i"
	@echo "... node/src/dsv_p2p.s"
	@echo "... node/src/dsv_rpc.o"
	@echo "... node/src/dsv_rpc.i"
	@echo "... node/src/dsv_rpc.s"
	@echo "... node/src/dsv_storage.o"
	@echo "... node/src/dsv_storage.i"
	@echo "... node/src/dsv_storage.s"
	@echo "... tests/unit/test_consensus.o"
	@echo "... tests/unit/test_consensus.i"
	@echo "... tests/unit/test_consensus.s"
	@echo "... tests/unit/test_crypto.o"
	@echo "... tests/unit/test_crypto.i"
	@echo "... tests/unit/test_crypto.s"
	@echo "... tests/unit/test_serialize.o"
	@echo "... tests/unit/test_serialize.i"
	@echo "... tests/unit/test_serialize.s"
	@echo "... tests/unit/test_u320.o"
	@echo "... tests/unit/test_u320.i"
	@echo "... tests/unit/test_u320.s"
	@echo "... wallet/main.o"
	@echo "... wallet/main.i"
	@echo "... wallet/main.s"
	@echo "... wallet/src/dsv_wallet.o"
	@echo "... wallet/src/dsv_wallet.i"
	@echo "... wallet/src/dsv_wallet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

